[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCRP MIS Documentation"
authors = [{name = "SCRP MIS", email = "scrpmis2021@gmail.com"}]
dynamic = ["version", "description"]
